### ISSUE TITLE
Requesting new shortcodes

### ISSUE THREAD

**Issue by maduonline** [notifylk/notify-woocommerce#5]
- [ ] Please allow following two shortcodes in SMS content.
{{billing_city}} => Billing city of the order
{{customer_phone}} => Customer phone number.
- [ ] Add a description text with all the shortcodes available to use.

**Comment by disapamok** [comment]
Added eligibility to use customer billing city via {{billing_city}} and customer phone number via {{customer_phone}} in message body. Also, Added short-code description in the bottom of NotifyLK settings page. (Branch : Issue_#5)
